name: pokedex_flutter_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  poke_system:
    path: poke_system

  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  shimmer: ^2.0.0
  equatable: ^2.0.5
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  flutter_bloc: ^8.1.2
  dio: ^5.1.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  cached_network_image: ^3.2.3
  build_runner: ^2.3.3
  provider: ^6.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/png/
